import Head from 'next/head'
import Image from 'next/image'
import DraggableSideBar from '../components/DraggableSideBar/DraggableSideBar'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{color:"red"}}>
          fuck you mother fuck you son of bitch my ass is too big mother fucker
      </main>
    </div>
  )
}
